### ISSUE TITLE
Add Node.js Addon docs

### ISSUE THREAD

**Issue by springmeyer** [mapbox/cpp#6]
Chatting with @GretaCB about moving very node.js specific docs currently in the readme to https://github.com/mapbox/node-cpp-skel. We imagine https://github.com/mapbox/node-cpp-skel can offer both documentation for writing node c++ code and a working example.

**Comment by springmeyer** [comment]
Note: some mentions of node should likely stay in the core /cpp doc like the issues of standard library and binary portability mentioned in https://github.com/mapbox/cpp#os-x-1.

**Comment by mapsam** [comment]
I'm going to play devil's advocate here, just for fun. What if we were to keep all of our documentation & philosophy in this repo, node or otherwise, and just keep the skels clean for their code? The writeups around the skeletons can exist in this repository, which allows us to keep similar language all in one spot instead of writing potentially redundant docs across repos. The skeletons themselves can be lightweight in their README's, including just a "whats in the box" kind of list.

**Comment by GretaCB** [comment]
@mapsam iiiiinteresting. Perhaps a node-cpp directory within this repo?

**Comment by springmeyer** [comment]
💯  to reducing redundancy and increasing motivation and ease of maintainability. I'm open to keeping skels light @mapsam. The idea behind using `node-cpp-skel` for docs was a to avoid having to create another repo for docs.

> @mapsam iiiiinteresting. Perhaps a node-cpp directory within this repo?

👍  to keeping everything in this repo and instead brainstorming better organization.

**Comment by mapsam** [comment]
How about we start working on a `node-cpp.md` file in this repo to keep everything together. Once we start collecting more information we can revisit the best way to organize everything.

**Comment by mapsam** [comment]
https://github.com/mapbox/cpp/blob/master/node-cpp.md are real!
